project/urls.py
from django.conf.urls import patterns, include, url
from socialneo.views import HomeView, ProfileView, SubmitView, MyProfileView, NEOListView, NEOItemView, NEOItemObserveView

from django.contrib.auth.views import logout

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^profile/?$', MyProfileView.as_view(), name='my_profile'),
    url(r'^profile/(?P<user>.+)?$', ProfileView.as_view(), name='my_profile'),

    url(r'^submit/?$', SubmitView.as_view(), name='submit'),
    # url(r'^project/', include('project.foo.urls')),

    url(r'^logout/?$', logout, {'next_page': '/'}, name='socialauth_logout'),
    url(r'', include('social_auth.urls')),

    url(r'^neo/?$', NEOListView.as_view(), name='neo_list'),
    url(r'^neo/(?P<neo_id>\d+)$', NEOItemView.as_view(), name='neo_item'),
    url(r'^neo/(?P<neo_id>\d+)/observe/?$', NEOItemObserveView.as_view(), name='neo_item_observe'),
    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
)

socialneo/models.py
from django.db import models
from django.contrib.auth.models import User

from base.models import BaseModel


class NearEarthObject(BaseModel):

    discovered_by = models.ForeignKey(User, null=False)

    name = models.CharField(max_length=100)
    discovery_date = models.DateField()
    right_ascension_hours = models.FloatField()
    right_ascension_minutes = models.FloatField()
    right_ascension_seconds = models.FloatField()
    declination_hours = models.FloatField()
    declination_minutes = models.FloatField()
    declination_seconds = models.FloatField()
    magnitude = models.FloatField()
    arc = models.FloatField()
    nominal_h = models.FloatField()

    desirability = models.IntegerField(default=0)
    num_observations = models.PositiveIntegerField(default=0)
    notes = models.CharField(max_length=255, null=True, blank=True)
    media = models.FileField(upload_to='neo_media')

    HOUR_DEGREES = 360/24
    MINUTES_DEGREES = HOUR_DEGREES/60
    SECONDS_DEGREES = MINUTES_DEGREES/60

    @property
    def right_ascension_degrees(self):
        degrees = self.HOUR_DEGREES * right_ascension_hours + \
                  self.MINUTES_DEGREES * right_ascension_minutes + \
                  self.SECONDS_DEGREES * right_ascension_seconds

    @property
    def declination_degrees(self):
        degrees = self.HOUR_DEGREES * declination_hours + \
                  self.MINUTES_DEGREES * declination_minutes + \
                  self.SECONDS_DEGREES * declination_seconds


class Observation(BaseModel):
    neo = models.ForeignKey(NearEarthObject)
    observer = models.ForeignKey(User)
    observation_date = models.DateField()

    class Meta:
        unique_together = ('neo', 'observer')

socialneo/forms.py
import re
from django import forms
from django.core.exceptions import ValidationError


def validate_degrees(value):
    pattern = '^\d\d? \d\d?\.\d\d?$'
    regex = re.compile(pattern)
    if regex.match(value) is None:
        raise ValidationError('Degrees input is wrong')

class NeoSubmitForm(forms.Form):
    
    name = forms.CharField()
    discovery_date = forms.DateField()
    right_ascension = forms.CharField(validators=[validate_degrees])
    declination = forms.CharField(validators=[validate_degrees])
    magnitude = forms.FloatField()
    arc = forms.FloatField()
    nominal_h = forms.FloatField()
    media = forms.FileField()

socialneo/views.py
import json
import urllib
import requests

from datetime import datetime

from django.views.generic import TemplateView
from django.core.exceptions import PermissionDenied
from django.http import Http404
from django.shortcuts import render_to_response, redirect
from django.contrib.auth.models import User
from django.conf import settings
from django.core.urlresolvers import reverse
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.db.models import Count

from socialneo.models import NearEarthObject, Observation
from socialneo.forms import NeoSubmitForm

from social_auth.models import UserSocialAuth


class AuthMixin(object):
    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(AuthMixin, self).dispatch(*args, **kwargs)

class HomeView(TemplateView):
    template_name = "home.html"

    def get_context_data(self):
        context = {}
        context['settings'] = settings
        return context


class ProfileView(TemplateView):
    template_name = "profile.html"

    def get_context_data(self, user):
        context = {}
        context['profile_user'] = User.objects.get(username=user)
        context['neos'] = NearEarthObject.objects.filter(discovered_by=context['profile_user'])
        context['settings'] = settings
        return context


class MyProfileView(ProfileView):

    def get_context_data(self):
        context = {}
        context['neos'] = NearEarthObject.objects.filter(discovered_by=self.request.user)
        context['profile_user'] = self.request.user
        context['settings'] = settings
        return context



class SubmitView(AuthMixin, TemplateView):
    template_name = "submit.html"

    def get_context_data(self):
        context = {}
        context['settings'] = settings
        return context

    def _parse_time(self, value):

        value = value.split(' ')
        hours = value[0]

        value = value[1].split('.')
        minutes = value[0]
        seconds = value[1]

        return hours, minutes, seconds

    def post(self, request, *args, **kwargs):
        if not request.user.is_authenticated():
            raise PermissionDenied

        form = NeoSubmitForm(request.POST, request.FILES)

        if form.is_valid():

            declination = self._parse_time(form.cleaned_data.pop('declination'))
            right_ascension = self._parse_time(form.cleaned_data.pop('right_ascension'))


            extra_data = {
                'discovered_by': request.user,
                'right_ascension_hours': right_ascension[0],
                'right_ascension_minutes': right_ascension[1],
                'right_ascension_seconds': right_ascension[2],
                'declination_hours': declination[0],
                'declination_minutes': declination[1],
                'declination_seconds': declination[2],
            }

            form.cleaned_data.update(extra_data)

            neo = NearEarthObject(**form.cleaned_data)
            neo.save()

            # Facebook open graph action

            social_user = UserSocialAuth.objects.get(user=request.user)

            if 'access_token' not in social_user.tokens:
                social_user.refresh_token()

            access_token = social_user.tokens['access_token']

            neo_url = "http://"
            neo_url += request.META['HTTP_HOST']
            neo_url += reverse('neo_item', kwargs={'neo_id': neo.id})

            data = {
                'access_token': access_token,
                'METHOD': 'POST',
                'near_earth_object': neo_url
            }

            data = urllib.urlencode(data)

            response = requests.post('https://graph.facebook.com/me/socialneo:discover?' + data)

            return redirect('/neo/' + str(neo.id))
        else:
            return render_to_response(self.template_name, {"message": "failed to create"})


class NEOListView(TemplateView):
    template_name = "neo/list.html"

    def get_context_data(self):
        context = {}
        context['settings'] = settings
        context['neos'] = NearEarthObject.objects.order_by('-created_at')[:20]

        trending_list = Observation.objects.values_list('neo__id', flat=True).annotate(count=Count('neo__id')).order_by('-count')[:5]
        context['trending'] = NearEarthObject.objects.filter(id__in=list(trending_list))

        return context


class NEOItemView(TemplateView):
    template_name = "neo/item.html"

    def get_context_data(self, neo_id):
        context = {}
        context['r'] = self.request
        context['settings'] = settings
        context['neo'] = NearEarthObject.objects.get(pk=neo_id)
        context['neo_image'] = NearEarthObject.objects.get(pk=neo_id).media.url.split('?')[0]
        return context

class NEOItemObserveView(AuthMixin, TemplateView):
    template_name = "neo/item.html"

    def get(self, request, *args, **kwargs):
        neo = NearEarthObject.objects.get(pk=self.kwargs.get('neo_id'))

        if Observation.objects.filter(neo=neo, observer=request.user).count() > 0:
            return redirect('/neo/' + self.kwargs.get('neo_id'))

        observation = Observation(neo=neo, observer=request.user, observation_date=datetime.now())
        observation.save()

        # Facebook open graph action

        social_user = UserSocialAuth.objects.get(user=neo.discovered_by)

        if 'access_token' not in social_user.tokens:
            social_user.refresh_token()

        access_token = social_user.tokens['access_token']

        neo_url = "http://"
        neo_url += request.META['HTTP_HOST']
        neo_url += reverse('neo_item', kwargs={'neo_id': neo.id})

        data = {
            'access_token': access_token,
            'METHOD': 'POST',
            'near_earth_object': neo_url
        }

        data = urllib.urlencode(data)

        response = requests.post('https://graph.facebook.com/me/socialneo:observe?' + data)

        return redirect('/neo/' + self.kwargs.get('neo_id'))

socialneo/templates/home.html
{% extends 'layout.html' %}

{% block content %}
<div class="row">
    <div class="large-12 columns">
        <h1>Lets Make NEO Discovery Social</h1>
        
        <div class="panel">
            <h3>1. Discover and Share</h3>
            <p>Submit a report of a NEO and share your findings on Facebook.</p>
        </div>
        
        <div class="panel">
            <h3>2. Observe and Engage</h3>
            <p>Help confirm NEOs from other astronomers.</p>
        </div>

        <div class="panel">
            <h3>3. Experts Confirm</h3>
            <p>With the help of the astronomy community, experts can confirm NEOs.</p>
        </div>
    </div>
</div>

{% endblock %}

socialneo/templates/layout.html
<!DOCTYPE html PUBLIC "-/>
<html>
<head prefix="og: http://ogp.me/ns# fb: http://ogp.me/ns/fb# {{ settings.FB_NAMESPACE }}: http://ogp.me/ns/fb/{{ settings.FB_NAMESPACE }}#">
    {% block og %}
    {% endblock %}
    <title>Social NEO</title>
    <link rel="stylesheet" type="text/css" href="/static/stylesheets/app.css">
</head>

<body>
{% include 'nav.html' %}


{% block content %}
{% endblock %}

</body>
</html>

socialneo/templates/nav.html
<nav class="top-bar">
  <ul class="title-area">
    <!-- Title Area -->
    <li class="name">
      <h1><a href="/">Social NEO</a></h1>
    </li>
    <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
    <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
  </ul>

  <section class="top-bar-section">
    <!-- Left Nav Section -->
    <ul class="left">
      <li class="divider"></li>
      <li><a href="/profile">My Profile</a></li>
      <li class="divider"></li>
      <li><a href="/submit">Submit Report</a></li>
      <li class="divider"></li>
      <li><a href="/neo">Discovered NEOs</a></li>
    </ul>

    <!-- Right Nav Section -->
    <ul class="right">
      <li class="divider hide-for-small"></li>
      
      {% if user.is_authenticated %}
      
      <li><a href="#">Hello {{user.first_name}} {{user.last_name}} <img src="http://graph.facebook.com/{{user.username}}/picture" style="height:25px;"></a></li>
      
      <li class="divider hide-for-small"></li>
      
      <li class="has-form">
        <a class="button" href="{% url socialauth_logout %}">Logout</a>
      </li>
      
      {% else %}
      
      <li class="has-form">
        <a class="button" href="{% url socialauth_begin 'facebook' %}">Login with Facebook</a>
      </li>

      {% endif %}
    </ul>
  </section>
</nav>

socialneo/templates/profile.html
{% extends 'layout.html' %}

{% block content %}
<div class="row">
    <h1>{{profile_user.first_name}} {{profile_user.last_name}}</h1>
</div>

<div class="row">
    <div class="large-3 columns">
        <img src="http://graph.facebook.com/{{profile_user.username}}/picture?type=large">
    </div>

    <div class="large-7 columns">
        <h3>Reported NEOs</h3>
        {% for neo in neos %}
            <div class="row">
                <div class="small-3 columns">
                    <a href="/neo/{{ neo.id }}"><img src="{{ neo.media.url }}"></a>
                </div>
                <div class="small-9 columns">
                    <strong><a href="/neo/{{ neo.id }}">{{ neo.name }}</a></strong>
                    <br />Discovered: {{ neo.discovery_date }}
                    <br />Observations: {{ neo.observation_set.all.count}}
                </div>
            </div>
            <hr />
        {% endfor %}
    </div>
</div>

{% endblock %}

socialneo/templates/submit.html
{% extends 'layout.html' %}

{% block content %}
<div class="row">
    <div class="large-12 columns">
        <h1>Submit Report</h1>
        <h3>{{message}}</h3>
        <form action="/submit/" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="row">
            <div class="large-6 columns">
                <label for="id_name">Name:</label>
                <input type="text" name="name" id="id_right_ascension" />
            </div>
            <div class="large-6 columns">
                <label for="id_discovery_date">Discovery Date:</label>
                <input type="date" name="discovery_date" id="id_discovery_date" maxlength="100" />
            </div>
        </div>

        <div class="row">
            <div class="large-6 columns">
                <label for="id_right_ascension">Right Ascension (hh mm.ss):</label>
                <input type="text" name="right_ascension" id="id_right_ascension" />
            </div>
            <div class="large-6 columns">
                <label for="id_declination">Declination (hh mm.ss):</label>
                <input type="text" name="declination" id="id_declination" />
            </div>
        </div>

        <div class="row">
            <div class="large-4 columns">
                <label for="id_magnitude">Magnitude:</label>
                <input type="text" name="magnitude" id="id_magnitude" />
            </div>
            <div class="large-4 columns">
                <label for="id_arc">Arc:</label>
                <input type="text" name="arc" id="id_arc" />
            </div>
            <div class="large-4 columns">
                <label for="id_nominal_h">Nominal H:</label>
                <input type="text" name="nominal_h" id="id_norminal_h" />
            </div>
        </div>


        <p>
            <label for="id_media">Upload image:</label>
            <input type="file" name="media" id="id_media" />
        </p>
        <input type="submit" class="button success" value="Submit" />
        </form>
    </div>
</div>

{% endblock %}